### ISSUE TITLE
exec-as typo

### ISSUE THREAD

**Issue by ahmetb** [jordanwilson230/kubectl-plugins#17]
says `ezec`

kubectl exec-as -h
/Users/ahmetb/.krew/bin/kubectl-exec_as: option requires an argument -- h

Usage: kubectl ezec-as [OPTIONS] <pod name> [-- <commands...>]

Run a command in a running container

**Comment by jordanwilson230** [comment]
@ahmetb I did notice that while creating https://github.com/kubernetes-sigs/krew-index/pull/348 but from what i can see it contains the commit https://github.com/jordanwilson230/kubectl-plugins/commit/1425a93930664785a955cff9a648262774ceffc1 where it was fixed.  Are you still seeing this in the updated package?
