### ISSUE TITLE
Unable to use exec_as with resource quotas

### ISSUE THREAD

**Issue by glensc** [jordanwilson230/kubectl-plugins#20]
There's no visible way to set resource quotas when creating the temporary pod. Please add a way to specify limits and requests.

```
$ kubectl exec-as -n dlb dlb-node-review-lv-master-mqe0vx-77fc8f6967-cvprn
Connecting...
Pod: dlb-node-review-lv-master-mqe0vx-77fc8f6967-cvprn
Namespace: dlb
User: root
Container: NONE
Command: /bin/sh

Error from server (Forbidden): pods "glen-1" is forbidden: failed quota: quota-dlb: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

$ kubectl  exec-as -n dlb --resources=limits.cpu=100m dlb-node-review-lv-master-mqe0vx-77fc8f6967-cvprn
/Users/glen/.krew/bin/kubectl-exec_as: illegal option -- -

Usage: kubectl exec-as [OPTIONS] <pod name> [-- <commands...>]

Run a command in a running container

Options:
  -h  Show usage
  -d  Enable debug mode. Print a trace of each commands
  -n  If present, the namespace scope for this CLI request
  -u  Username or UID (format: <name|uid>[:<group|gid>])
  -c  Container name. If omitted, the first container in the pod will be chosen
```

**Comment by jordanwilson230** [comment]
@glensc By the looks of your error, i'm assuming youre running in a namespace that has quotas in place. Can you conform?

**Comment by jordanwilson230** [comment]
Oops, I was reading from my phone and didn't pay enough attention to the title...which answers my question :smile: 

The real question, though, is how much value a change like this would bring to the main audience.  If it's more than I suspect and we can get some thumbs up for this, no problem adding it.

**Comment by jordanwilson230** [comment]
@glensc 
You can use the kubectl-ssh file in the PR here: 

https://github.com/jordanwilson230/kubectl-plugins/pull/21

This should work for your case.

**Comment by glensc** [comment]
looks like I reported this to the wrong project, I used `kubectl exec-as` not `kubectl ssh`.

however if your plugin doesn't support resources either, it can stay open here :)
