### ISSUE TITLE
The ssh plugin timesout after a while if no new input is received

### ISSUE THREAD

**Issue by shanebishop** [jordanwilson230/kubectl-plugins#25]
There is a bug with the ssh plugin where the session terminates unexpectedly after a while if no new input is provided.
When the user next tries to send new input, they will receive a message like this:
`E0821 13:07:24.069237    3819 v2.go:105] EOF`
Then the only way for the user to get back a prompt is to Ctrl+C out of the `kubectl ssh` process.

**Comment by jordanwilson230** [comment]
@shanebishop the issue you're experiencing is an issue of kubectl itself and can be reproduced using kubectl exec as well.  It isn't related to the plugins.
