### ISSUE TITLE
Error running temporary pod with ssh plugin

### ISSUE THREAD

**Issue by shenrie** [jordanwilson230/kubectl-plugins#34]
I wanted to bring this situation to your attention and share this issue for others that might also run into this problem. 

I have been successfully using your ssh plugin to run as root user in running pods for over six months and have been using with kubernetes managed service (EKS) on AWS. Thank you for providing this excellent set of utilities. I don't know the root cause, but somewhere along the line, I updated the EKS nodes and kubectl to these versions:
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Now when I run `kubectl ssh -u root jenkins-bffffdf94-t92th` the ssh no longer works because the temporary pod fails to run with the error: `MountVolume.SetUp failed for volume "docker" : hostPath type check failed: /var/run/docker.sock is not a file `

The only way that I was able to get the ssh to work again was to modify your ssh plugin script and remove the [line](https://github.com/jordanwilson230/kubectl-plugins/blob/master/kubectl-ssh#L151) which specifies the docker.sock as a file type, which kind of makes sense given the error message above. 

Not sure if you can/should make this change to the scripts, but others will probably run into this after upgrading some part of the stack.

**Comment by jordanwilson230** [comment]
@shenrie interesting! Thanks a lot for your post.  Im aware of the k8s changes coming in the newer versions but have not been able to find the time to test workarounds for it.  If it is able to run like you say, by removing the "file" line, that would be great.  If anyone else is able to test that against their upgraded non docker k8s clusters, please post here to let us know of the results!

**Comment by jordanwilson230** [comment]
@rjshrjndrn @pbabilas ^^ :)

**Comment by pbabilas** [comment]
gr8 at my env its working fine! ;] THANKS

**Comment by rjshrjndrn** [comment]
I think this should a PR, as all new Kube clusters use, by default containerd.
