### ISSUE TITLE
Start distributing plugins via Krew

### ISSUE THREAD

**Issue by ahmetb** [jordanwilson230/kubectl-plugins#5]
Hello again. 👋 We've discussed about this privately in email, opening an issue here for tracking the public interest.

I'd love to have some of these great plugins at **`krew`**, the plugin manager for kubectl. https://github.com/GoogleContainerTools/krew

Since we last talked, `krew` has added support for kubectl-1.12 style plugins –and `krew` is being donated to Kubernetes SIG CLI.

Some plugins with common names (like "ssh") maybe a problem but the rest looks pretty interesting. I've personally ported a few other people's bash-based plugins to `krew` and it's pretty simple!

You can get started at the [Developer Guide](https://github.com/GoogleContainerTools/krew/blob/18ed853dfa43202d46988f2864eb8b4565c80b5c/docs/DEVELOPER_GUIDE.md).

**Comment by jordanwilson230** [comment]
@ahmetb Hi again :D. Yes, the change introduced in v1.12 occured right as I was preparing to port some of my plugins over to krew (perfect timing, ha). Now that I've reworked the code to support that change, I will take another look at porting them over.  You're more than welcome to help, though I'm sure you're quite busy yourself, maintaining ```krew```!

Thanks for following up again, Ahmet.

**Comment by Moulick** [comment]
I would love to have a single plugin manager for kubectl and krew looks like the way to go.

**Comment by jordanwilson230** [comment]
@ahmetb I should have some time this weekend to put towards this.  I'll keep you updated.

**Comment by jordanwilson230** [comment]
PRs submitted:
https://github.com/GoogleContainerTools/krew-index/pull/45
https://github.com/GoogleContainerTools/krew-index/pull/46

Closing the issue

**Comment by austince** [comment]
These plugins are awesome, thanks @jordanwilson230 ! Happy to open a new issue, but wondering how much effor you think it'd be to port over the `ip` and `uptime` plugins as well? I can make a PR if you think it's reasonable
